allow-unwrap-in-tests = true
allow-expect-in-tests = true

disallowed-methods = [
    "core::option::Option::unwrap",
    "core::result::Result::unwrap",
    "core::option::Option::expect",
    "core::result::Result::expect",
]

disallowed-macros = [
    "std::panic",
    "std::dbg",
    "std::todo",
]
